export const air = [
    {
        "id":200,
        "fa":"رعد و برق همراه با باران خفیف",
        "en":"thunderstorm with light rain",
        "status": "storm-rain",
        "icon": require("../../../assets/images/weather4/storm-rain.png").default,
    },
    {
        "id":201,
        "fa":"رعد و برق همراه با باران",
        "en":"thunderstorm with rain",
        "status": "storm-rain",
        "icon": require("../../../assets/images/weather4/storm-rain.png").default,
    },
    {
        "id":202,
        "fa":"رعد و برق همراه با باران شدید",
        "en":"thunderstorm with heavy rain",
        "status": "storm-rain",
        "icon": require("../../../assets/images/weather4/storm-rain.png").default,
    },
    {
        "id":210,
        "fa":"رعد و برق خفیف",
        "en":"light thunderstorm",
        "status": "storm",
        "icon": require("../../../assets/images/weather4/storm.png").default,
    },
    {
        "id":211,
        "fa":"رعد و برق",
        "en":"thunderstorm",
        "status": "storm",
        "icon": require("../../../assets/images/weather4/storm.png").default,
    },
    {
        "id":212,
        "fa":"رعد و برق شدید",
        "en":"heavy thunderstorm",
        "status": "storm",
        "icon": require("../../../assets/images/weather4/storm.png").default,
    },
    {
        "id":221,
        "fa":"رعد و برق خشن",
        "en":"ragged thunderstorm",
        "status": "storm",
        "icon": require("../../../assets/images/weather4/storm.png").default,
    },
    {
        "id":230,
        "fa":"رعد و برق همراه با نم نم باران خفیف",
        "en":"thunderstorm with light drizzle",
        "status": "storm-rain",
        "icon": require("../../../assets/images/weather4/storm-rain.png").default,
    },
    {
        "id":231,
        "fa":"رعد و برق همراه با نم نم نم نم باران",
        "en":"thunderstorm with drizzle",
        "status": "storm-rain",
        "icon": require("../../../assets/images/weather4/storm-rain.png").default,
    },
    {
        "id":232,
        "fa":"رعد و برق همراه با باران شدید",
        "en":"thunderstorm with heavy drizzle",
        "status": "storm-rain",
        "icon": require("../../../assets/images/weather4/storm-rain.png").default,
    },
    {
        "id":300,
        "fa":"نم نم باران با شدت نور",
        "en":"light intensity drizzle",
        "status": "storm-rain",
        "icon": require("../../../assets/images/weather4/storm-rain.png").default,
    },
    {
        "id":301,
        "fa":"باران ریز و نمناک",
        "en":"drizzle",
        "status": "rain",
        "icon": require("../../../assets/images/weather4/rain.png").default,
    },
    {
        "id":302,
        "fa":"نم نم با شدت زیاد",
        "en":"heavy intensity drizzle",
        "status": "rain",
        "icon": require("../../../assets/images/weather4/rain.png").default,
    },
    {
        "id":310,
        "fa":"باران با شدت کم",
        "en":"light intensity drizzle rain",
        "status": "rain",
        "icon": require("../../../assets/images/weather4/rain.png").default,
    },
    {
        "id":311,
        "fa":"باران نم نم",
        "en":"drizzle rain",
        "status": "rain",
        "icon": require("../../../assets/images/weather4/rain.png").default,
    },
    {
        "id":312,
        "fa":"باران با شدت شدید",
        "en":"heavy intensity drizzle rain",
        "status": "heavy-rain",
        "icon": require("../../../assets/images/weather4/heavy-rain").default,
    },
    {
        "id":313,
        "fa":"دوش نم نم باران",
        "en":"shower rain and drizzle",
        "status": "rain",
        "icon": require("../../../assets/images/weather4/rain.png").default,
    },
    {
        "id":314,
        "fa":"دوش نم نم باران شدید",
        "en":"heavy shower rain and drizzle",
        "status": "heavy-rain",
        "icon": require("../../../assets/images/weather4/heavy-rain").default,
    },
    {
        "id":321,
        "fa":"نم نم باران",
        "en":"shower drizzle",
        "status": "rain",
        "icon": require("../../../assets/images/weather4/rain.png").default,
    },
    {
        "id":500,
        "fa":"باران سبک",
        "en":"light rain",
        "status": "rain",
        "icon": require("../../../assets/images/weather4/rain.png").default,
    },
    {
        "id":501,
        "fa":"باران متوسط",
        "en":"moderate rain",
        "status": "rain",
        "icon": require("../../../assets/images/weather4/rain.png").default,
    },
    {
        "id":502,
        "fa":"باران با شدت زیاد",
        "en":"heavy intensity rain",
        "status": "heavy-rain",
        "icon": require("../../../assets/images/weather4/heavy-rain").default,
    },
    {
        "id":503,
        "fa":"باران بسیار شدید",
        "en":"very heavy rain",
        "status": "heavy-rain",
        "icon": require("../../../assets/images/weather4/heavy-rain").default,
    },
    {
        "id":504,
        "fa":"باران شدید",
        "en":"extreme rain",
        "status": "heavy-rain",
        "icon": require("../../../assets/images/weather4/heavy-rain").default,
    },
    {
        "id":511,
        "fa":"قندیل",
        "en":"freezing rain",
        "status": "freez-rain",
        "icon": require("../../../assets/images/weather4/freez-rain").default,
    },
    {
        "id":520,
        "fa":"باران رگباری با شدت کم",
        "en":"light intensity shower rain",
        "status": "rain",
        "icon": require("../../../assets/images/weather4/rain.png").default,
    },
    {
        "id":521,
        "fa":"باران رگباری",
        "en":"shower rain",
        "status": "heavy-rain",
        "icon": require("../../../assets/images/weather4/heavy-rain").default,
    },
    {
        "id":522,
        "fa":"باران رگباری شدید",
        "en":"heavy intensity shower rain",
        "status": "heavy-rain",
        "icon": require("../../../assets/images/weather4/heavy-rain").default,
    },
    {
        "id":531,
        "fa":"دوش باران تند",
        "en":"ragged shower rain",
        "status": "heavy-rain",
        "icon": require("../../../assets/images/weather4/heavy-rain").default,
    },
    {
        "id":600,
        "fa":"برف سبک",
        "en":"light snow",
        "status": "snow",
        "icon": require("../../../assets/images/weather4/snow.png").default,
    },
    {
        "id":601,
        "fa":"برف",
        "en":"Snow",
        "status": "snow",
        "icon": require("../../../assets/images/weather4/snow.png").default,
    },
    {
        "id":602,
        "fa":"برف سنگین",
        "en":"Heavy snow",
        "status": "heavy-snow",
        "icon": require("../../../assets/images/weather4/heavy-snow.png").default,
    },
    {
        "id":611,
        "fa":"برفک",
        "en":"Sleet",
        "status": "snow",
        "icon": require("../../../assets/images/weather4/snow.png").default,
    },
    {
        "id":612,
        "fa":"رگبار برفک سبک",
        "en":"Light shower sleet",
        "status": "snow",
        "icon": require("../../../assets/images/weather4/snow.png").default,
    },
    {
        "id":613,
        "fa":"رگبار برفک",
        "en":"Shower sleet",
        "status": "heavy-snow",
        "icon": require("../../../assets/images/weather4/heavy-snow.png").default,
    },
    {
        "id":615,
        "fa":"برف و باران سبک",
        "en":"Light rain and snow",
        "status": "freez-rain",
        "icon": require("../../../assets/images/weather4/freez-rain").default,
    },
    {
        "id":616,
        "fa":"برف و باران",
        "en":"Rain and snow",
        "status": "freez-rain",
        "icon": require("../../../assets/images/weather4/freez-rain").default,
    },
    {
        "id":620,
        "fa":"رگبار برف خفیف",
        "en":"Light shower snow",
        "status": "snow",
        "icon": require("../../../assets/images/weather4/snow.png").default,
    },
    {
        "id":621,
        "fa":"رگبار برف",
        "en":"Shower snow",
        "status": "heavy-snow",
        "icon": require("../../../assets/images/weather4/heavy-snow.png").default,
    },
    {
        "id":622,
        "fa":"رگبار برف سنگین",
        "en":"Heavy shower snow",
        "status": "heavy-snow",
        "icon": require("../../../assets/images/weather4/heavy-snow.png").default,
    },
    {
        "id":701,
        "fa":"غبار آلود",
        "en":"mist",
        "status": "foggy",
        "icon": require("../../../assets/images/weather4/foggy.png").default,
    },
    {
        "id":711,
        "fa":"دود",
        "en":"Smoke",
        "status": "foggy",
        "icon": require("../../../assets/images/weather4/foggy.png").default,
    },
    {
        "id":721,
        "fa":"آسمان گرفتار در ابر",
        "en":"Haze",
        "status": "haze",
        "icon": require("../../../assets/images/weather4/haze-day.png").default,
        "n-icon": require("../../../assets/images/weather4/haze-night.png").default,
    },
    {
        "id":731,
        "fa":"گرد و غبار",
        "en":"sand/ dust whirls",
        "status": "foggy",
        "icon": require("../../../assets/images/weather4/foggy.png").default,
    },
    {
        "id":741,
        "fa":"مه آلود",
        "en":"fog",
        "status": "foggy",
        "icon": require("../../../assets/images/weather4/foggy.png").default,
    },
    {
        "id":751,
        "fa":"ریزگرد",
        "en":"sand",
        "status": "foggy",
        "icon": require("../../../assets/images/weather4/foggy.png").default,
    },
    {
        "id":761,
        "fa":"گرد و خاک",
        "en":"dust",
        "status": "foggy",
        "icon": require("../../../assets/images/weather4/foggy.png").default,
    },
    {
        "id":762,
        "fa":"خاکستر آتشفشانی",
        "en":"volcanic ash",
        "status": "foggy",
        "icon": require("../../../assets/images/weather4/foggy.png").default,
    },
    {
        "id":771,
        "fa":"بوران",
        "en":"squalls",
        "status": "tornado",
        "icon": require("../../../assets/images/weather4/tornado.png").default,
    },
    {
        "id":781,
        "fa":"گردباد",
        "en":"tornado",
        "status": "tornado",
        "icon": require("../../../assets/images/weather4/tornado.png").default,
    },
    {
        "id":800,
        "fa":"آسمان صاف",
        "en":"clear sky",
        "status": "clean",
        "icon": require("../../../assets/images/weather4/clean-day.png").default,
        "n-icon": require("../../../assets/images/weather4/clean-night.png").default,
    },
    {
        "id":801,
        "fa":"کمی ابری",
        "en":"few clouds: 11-25%",
        "status": "haze",
        "icon": require("../../../assets/images/weather4/haze-day.png").default,
        "n-icon": require("../../../assets/images/weather4/haze-night.png").default,
    },
    {
        "id":802,
        "fa":"ابرهای پراکندی",
        "en":"scattered clouds: 25-50%",
        "status": "haze",
        "icon": require("../../../assets/images/weather4/haze-day.png").default,
        "n-icon": require("../../../assets/images/weather4/haze-night.png").default,
    },
    {
        "id":803,
        "fa":"ابرهای شکسته",
        "en":"broken clouds: 51-84%",
        "status": "haze",
        "icon": require("../../../assets/images/weather4/haze-day.png").default,
        "n-icon": require("../../../assets/images/weather4/haze-night.png").default,
    },
    {
        "id":804,
        "fa":"آسمان پوشیده از ابر",
        "en":"overcast clouds: 85-100%",
        "status": "cloudy",
        "icon": require("../../../assets/images/weather4/cloud.png").default,
    }
]
// modules.exports = air;
// export {air};
export default module;